### ISSUE TITLE
Inquirer plugin crashes with plop 1.6.0

### ISSUE THREAD

**Issue by pavanpodila** [amwmedia/plop#48]
Looks like there is some mismatch in `plop`, `inquirer`, around the use of promises:

Offending code:
**plop/node_modules/inquirer/lib/ui/prompt.js:79:50**
```js linenos
PromptUI.prototype.fetchAnswer = function (question) {
  var Prompt = this.prompts[question.type];
  var prompt = new Prompt(question, this.rl, this.answers);
  return rx.Observable.defer(function () {
// This next lines fails as prompt.run() doesn't seem to return a promise
    return rx.Observable.fromPromise(prompt.run().then(function (answer) {
      return {name: question.name, answer: answer};
    }));
  });
};

```

Log:
```
(Use "/" key to search this directory)[ERROR] Cannot read property 'then' of undefined TypeError: Cannot read property 'then' of undefined
    at /Users/ppodil/Projects/react-mobx-seed/node_modules/plop/node_modules/inquirer/lib/ui/prompt.js:79:50
    at tryCatcher (/Users/ppodil/Projects/react-mobx-seed/node_modules/rx/dist/rx.js:63:31)
    at Defer.subscribeCore (/Users/ppodil/Projects/react-mobx-seed/node_modules/rx/dist/rx.js:2536:37)
    at Defer.tryCatcher (/Users/ppodil/Projects/react-mobx-seed/node_modules/rx/dist/rx.js:63:31)
    at setDisposable (/Users/ppodil/Projects/react-mobx-seed/node_modules/rx/dist/rx.js:2082:46)
    at Defer.Rx.ObservableBase.ObservableBase._subscribe (/Users/ppodil/Projects/react-mobx-seed/node_modules/rx/dist/rx.js:2097:9)
    at Defer.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/ppodil/Projects/react-mobx-seed/node_modules/rx/dist/rx.js:2034:19)
    at MergeObserver.handleSubscribe (/Users/ppodil/Projects/react-mobx-seed/node_modules/rx/dist/rx.js:3525:28)
    at MergeObserver.next (/Users/ppodil/Projects/react-mobx-seed/node_modules/rx/dist/rx.js:3531:14)
    at MergeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/ppodil/Projects/react-mobx-seed/node_modules/rx/dist/rx.js:1762:31)


```

**Comment by amwmedia** [comment]
I believe this is likely a problem with a plugin that has not been updated to the 1.x release of inquirer. If you need to use plugins that use the 0.x version of inquirer you may need to revert the version of plop that you are using to 1.5.0. I'm open to other possible solutions, but I don't know of any at this time.

**Comment by amwmedia** [comment]
I'm happy to re-open this issue if there are other possible ways to address this issue.

**Comment by pavanpodila** [comment]
Ok, for now I am switching back to **1.5.0**. Hope @nicksrandall gets a chance to look and fix this.

**Comment by amwmedia** [comment]
if not, someone will probably make a fork that will work

**Comment by nicksrandall** [comment]
fixed via https://github.com/nicksrandall/inquirer-directory/releases/tag/v2.1.0

**Comment by pavanpodila** [comment]
Awesome @nicksrandall. Could you please publish to NPM as well :-)

**Comment by pavanpodila** [comment]
Finally was able to updated inquirer-directory and things are stable again. Thanks @nicksrandall
